-- AlterTable
ALTER TABLE "PatientActivity" ALTER COLUMN "weight" DROP NOT NULL,
ALTER COLUMN "weight_unit" DROP NOT NULL,
ALTER COLUMN "water" DROP NOT NULL,
ALTER COLUMN "steps" DROP NOT NULL,
ALTER COLUMN "heart_rate" DROP NOT NULL,
ALTER COLUMN "notetaking" DROP NOT NULL,
ALTER COLUMN "wombPicture" DROP NOT NULL;
